---
- include: install-common.yml

- include: install-src.yml
  when: redis_installation_source == 'src'

- include: install-pkg-debian.yml
  when: redis_installation_source == 'pkg' and ansible_os_family == "Debian"
