---
- name: enable overcommit in sysctl
  sysctl:
    name: vm.overcommit_memory
    value: 1
    state: present
    reload: yes
    ignoreerrors: yes

- name: Install latest Redis package
  yum:
    name: redis
    state: latest
  when: redis_version == "latest"

- name: Install defined Redis package version
  yum:
    name: redis-{{ redis_version }}
    state: present
  when: redis_version != "latest"

- name: remove default redis conf file
  file:
    state: absent
    path: /etc/redis.conf

- name: remove default redis-sentinel conf file
  file:
    state: absent
    path: /etc/redis-sentinel.conf
