---
- name: restart redis
  service:
    name: "{{ redis_systemd_service_name }}"
    state: restarted
  when: redis_as_service

- name: restart sentinel
  service:
    name: "{{ redis_sentinel_systemd_service_name }}"
    state: restarted
  when: redis_as_service
